Repository Leekee0905/last-supper, pull requests merged in 2024-09, with the labels that each got.

#1 [bugfix]모달 에러 해결
  .github/pull_request_template.md
  index.html
  public/vite.svg
  src/assets/react.svg
  src/pages/Home/Home.jsx
  src/pages/MainPage/components/Modal/Modal.jsx
  src/store/useModalStore.js
Labels: 버그, 문서수정

#2 homepage.jsx 작업 쿼리 스트림 작업 완료 / 및 메인 페이지 사이드바 및 모달 작업 완료
  package.json
  src/layout/Layout.jsx
  src/layout/components/HamburgerItem.jsx
  src/layout/components/HamburgerMenu.jsx
  src/layout/components/sidebar.jsx
  src/pages/Home/Home.jsx
  src/pages/Home/components/search.jsx
  src/shared/Router.jsx
  yarn.lock
Labels: 기능개발, 문서수정

#4 [feat] Layout 전역상태관리 추가 및 전역일 계산기 캘린더 파일 추가
  src/layout/Layout.jsx
  src/layout/components/HamburgerMenu.jsx
  src/layout/components/Sidebar.jsx
  src/pages/Home/components/Search.jsx
  src/pages/MainPage/MainPage.jsx
  src/pages/MainPage/components/Calculator.jsx
  src/pages/MainPage/components/Modal/Modal.jsx
Labels: 기능개발, 리팩토링

#5 [feat] login (임시 작업 병합)
  src/api/.gitkeep
  src/api/apiInstance.js
  src/api/auth.js
  src/hooks/queries/auth/useLoginQuery.js
  src/layout/Layout.jsx
  src/layout/components/HamburgerItem.jsx
  src/layout/components/HamburgerMenu.jsx
  src/pages/MainPage/components/AuthForm.jsx
  src/pages/MainPage/components/Calculator.jsx
  src/pages/MainPage/components/Login/LoginModal.jsx
  src/pages/MainPage/components/Modal/Modal.jsx
  src/store/useUserStore.js
Labels: 기능개발, 리팩토링

#6 Feat/my page
  db.json
  index.html
  package.json
  src/api/favorites.js
  src/api/reviews.js
  src/components/.gitkeep
  src/components/Pagination.jsx
  src/layout/Layout.jsx
  src/pages/MainPage/components/Modal/Modal.jsx
  src/pages/MainPage/components/MyPage/MyActivities.jsx
  src/pages/MainPage/components/MyPage/MyPage.jsx
  src/pages/MainPage/components/MyPage/Profile.jsx
  src/queries/favoritesQuery.js
  src/queries/queryKeys.js
  src/queries/reviewsQuery.js
  src/reset.css
  yarn.lock
Labels: 기능개발, 구조변경, 스타일링

#7 [feat] login 모달
  index.html
  src/api/apiInstance.js
  src/hooks/queries/auth/useHasTokenAuthenticatedQuery.js
  src/hooks/queries/auth/useLoginQuery.js
  src/layout/Layout.jsx
  src/layout/components/HamburgerItem.jsx
  src/layout/components/HamburgerMenu.jsx
  src/pages/MainPage/components/Login/LoginModal.jsx
  src/store/useModalStore.js
  src/store/useUserStore.js
Labels: 기능개발, 구조변경

#8 [Feat] kakao map
  .gitignore
  index.html
  src/layout/components/HamburgerMenu.jsx
  src/pages/Home/Home.jsx
  src/pages/Home/components/Search.jsx
  src/pages/MainPage/MainPage.jsx
Labels: 기능개발, 구조변경

#10 [Feat] kakao map
  package.json
  src/layout/components/Sidebar.jsx
  src/pages/MainPage/MainPage.jsx
  src/shared/Router.jsx
  src/store/useRestaurantsInfo.js
  yarn.lock
Labels: 구조변경

#11 [style] authform 모달 폼 스타일링
  package.json
  src/api/auth.js
  src/layout/Layout.jsx
  src/pages/MainPage/components/AuthForm.jsx
  src/pages/MainPage/components/Login/LoginModal.jsx
  src/pages/MainPage/components/Signup/SignupModal.jsx
  yarn.lock
Labels: 버그, 스타일링

#12 [ feat] my page
  db.json
  package.json
  pull_request_template.md
  src/api/MyActivitesApi.js
  src/api/apiInstance.js
  src/api/favorites.js
  src/api/reviews.js
  src/components/LoadingModal.jsx
  src/hooks/.gitkeep
  src/hooks/queries/myActivities/myActivityQuery.js
  src/hooks/queries/queryKeys.js
  src/layout/components/HamburgerItem.jsx
  src/layout/components/HamburgerMenu.jsx
  src/layout/components/Sidebar.jsx
  src/main.jsx
  src/pages/MainPage/components/Login/LoginModal.jsx
  src/pages/MainPage/components/Modal/Modal.jsx
  src/pages/MainPage/components/MyPage/MyActivities.jsx
  src/pages/MainPage/components/MyPage/MyPage.jsx
  src/pages/MainPage/components/MyPage/Profile.jsx
  src/pages/MainPage/components/Signup/SignupModal.jsx
  src/queries/favoritesQuery.js
  src/queries/queryKeys.js
  src/queries/reviewsQuery.js
  src/reset.css
  yarn.lock
Labels: 기능개발, 스타일링, 리팩토링

#14 feat/전역기 계산기 제작
  src/api/apiInstance.js
  src/layout/Layout.jsx
  src/pages/MainPage/components/Calculator.jsx
  src/pages/MainPage/components/Calculator/Calculator.jsx
  src/pages/MainPage/components/Calculator/Sidebar.jsx
  src/pages/MainPage/components/Modal/Modal.jsx
Labels: 기능개발, 구조변경, 스타일링

#17 Feat/save restaurants
  db.json
  src/api/apiInstance.js
  src/api/restaurants.js
  src/hooks/queries/restaurants/useGetRestaurantsDataQuery.js
  src/hooks/queries/restaurants/useSaveRestaurantsDataQuery.js
  src/layout/components/Sidebar.jsx
  src/pages/MainPage/MainPage.jsx
  src/pages/MainPage/components/Modal/Modal.jsx
  src/utils/campSearchWordConverter.js
Labels: 기능개발

#21 Feat/ pagination
  src/api/apiInstance.js
  src/components/Pagination.jsx
  src/hooks/queries/myActivities/myActivityQuery.js
  src/pages/MainPage/components/MyPage/MyActivities.jsx
  src/pages/MainPage/components/MyPage/MyPage.jsx
  src/reset.css
Labels: 기능개발, 리팩토링

#22 Feat/my page
  db.json
  src/api/MyActivitesApi.js
  src/api/apiInstance.js
  src/hooks/queries/myActivities/myActivityQuery.js
  src/hooks/queries/queryKeys.js
  src/main.jsx
  src/pages/MainPage/components/Detail/DetailModal.jsx
  src/pages/MainPage/components/MyPage/MyActivities.jsx
  src/pages/MainPage/components/MyPage/MyPage.jsx
  src/pages/MainPage/components/MyPage/Profile.jsx
  src/reset.css
Labels: 기능개발, 스타일링

#23 [feat] 검색 시 자동완성 리스트 기능 구현
  db.json
  public/assets/markerLine2.png
  src/api/myActivitesApi.js
  src/components/AutoComplete.jsx
  src/layout/Layout.jsx
  src/layout/components/HamburgerMenu.jsx
  src/layout/components/Sidebar.jsx
  src/layout/components/SidebarHeader.jsx
  src/pages/Home/Home.jsx
  src/pages/Home/components/Search.jsx
  src/pages/MainPage/MainPage.jsx
  src/pages/MainPage/components/AuthForm.jsx
  src/pages/MainPage/components/Detail/Review.jsx
  src/pages/MainPage/components/MapMarker/EventMarkerContainer.jsx
  src/reset.css
  src/utils/campSearchWordConverter.js
Labels: 기능개발, 구조변경, 스타일링, 리팩토링

#24 Feat/kakao map
  db.json
  src/api/myActivitesApi.js
  src/pages/MainPage/components/Detail/DetailModal.jsx
  src/pages/MainPage/components/Detail/Favorite.jsx
  src/pages/MainPage/components/Detail/Review.jsx
  src/pages/MainPage/components/Detail/ReviewItem.jsx
Labels: 구조변경, 리팩토링

#25 [update] 마이페이지 리뷰 업데이트 추가
  db.json
  pull_request_template.md
  src/api/apiInstance.js
  src/api/auth.js
  src/api/myActivitesApi.js
  src/components/LoadingModal.jsx
  src/hooks/queries/myActivities/myActivityQuery.js
  src/hooks/queries/queryKeys.js
  src/layout/components/HamburgerItem.jsx
  src/pages/MainPage/components/AuthForm.jsx
  src/pages/MainPage/components/Detail/Review.jsx
  src/pages/MainPage/components/Login/LoginModal.jsx
  src/pages/MainPage/components/Modal/Modal.jsx
  src/pages/MainPage/components/MyPage/MyActivities.jsx
  src/pages/MainPage/components/MyPage/MyActivityList.jsx
  src/pages/MainPage/components/MyPage/MyPage.jsx
  src/pages/MainPage/components/MyPage/Profile.jsx
  src/reset.css
Labels: 기능개발, 스타일링

#27 [refactor] 레이아웃, 햄버거메뉴, authform 리팩토링
  db.json
  src/layout/Layout.jsx
  src/layout/components/HamburgerContents.jsx
  src/layout/components/HamburgerItem.jsx
  src/layout/components/HamburgerMenu.jsx
  src/layout/components/Sidebar.jsx
  src/layout/components/SidebarHeader.jsx
  src/pages/MainPage/components/AuthForm.jsx
  src/pages/MainPage/components/Modal/Modal.jsx
  src/store/useHamburgerStore.js
  vercel.json
Labels: 리팩토링

#28 feat/ 전역일 계산기 99% 완성
  src/pages/MainPage/components/Calculator/Calculator.jsx
  src/pages/MainPage/components/Calculator/DateForm.jsx
  src/pages/MainPage/components/Calculator/EventTimeline.jsx
  src/pages/MainPage/components/Calculator/ProcessBar.jsx
  src/pages/MainPage/components/Calculator/RankTags.jsx
Labels: 버그, 기능개발, 스타일링

#30 [fix] 햄버거 메뉴 클릭후 다시 들어가는 로직 수정
  src/layout/components/HamburgerItem.jsx
Labels: 버그

#34 [fix] import 소문자 변경
  src/pages/MainPage/components/Detail/ReviewItem.jsx
Labels: 버그

#35 [fix] import 소문자 변경
  src/pages/MainPage/components/Detail/ReviewItem.jsx
Labels: 버그

#36 [update] 토큰 만료시 모달 닫기
  src/layout/Layout.jsx
Labels: 기능개발

#37 [update] 토큰 만료시 모달 닫기
  src/layout/Layout.jsx
Labels: 기능개발

#39 [update] 낙관적 업데이트
  src/hooks/queries/myActivities/myActivityQuery.js
  src/pages/MainPage/components/MyPage/MyActivities.jsx
  src/pages/MainPage/components/MyPage/MyActivityList.jsx
Labels: 기능개발

#42 [refactor] 1차 코드리뷰
  src/api/apiInstance.js
  src/api/auth.js
  src/components/AutoComplete.jsx
  src/layout/Layout.jsx
  src/layout/components/HamburgerContents.jsx
  src/layout/components/Sidebar.jsx
  src/pages/MainPage/MainPage.jsx
  src/pages/MainPage/components/AuthForm.jsx
  src/pages/MainPage/components/Calculator/Calculator.jsx
  src/pages/MainPage/components/Calculator/EventTimeline.jsx
  src/pages/MainPage/components/Calculator/RankTags.jsx
  src/pages/MainPage/components/Detail/DetailModal.jsx
  src/pages/MainPage/components/Detail/Favorite.jsx
  src/pages/MainPage/components/Detail/Review.jsx
  src/pages/MainPage/components/Detail/ReviewItem.jsx
  src/pages/MainPage/components/MapMarker/EventMarkerContainer.jsx
  src/pages/MainPage/components/MyPage/MyActivityList.jsx
  src/pages/MainPage/components/MyPage/MyPage.jsx
  src/store/useCalculatorStore.js
Labels: 리팩토링

#40 Feat/ 커스텀 알랏 추가
  src/main.jsx
  src/pages/MainPage/components/Calculator/DateForm.jsx
  src/store/useAlertStore.js
  src/styles/CustomAlert/AlertProvider.jsx
  src/styles/CustomAlert/hooks/useAlert.js
  src/styles/CustomAlert/hooks/useDebounce.js
Labels: 기능개발, 문서수정

#44 [fix] 커스텀 알럿 완성(토스트)
  src/main.jsx
  src/pages/MainPage/components/Calculator/Calculator.jsx
  src/pages/MainPage/components/Calculator/DateForm.jsx
  src/store/useAlertStore.js
  src/styles/CustomAlert/AlertProvider.jsx
Labels: 버그, 기능개발

#45 [update] 마커 다른거 클릭시 닫히도록 수정
  src/pages/MainPage/MainPage.jsx
  src/pages/MainPage/components/AuthForm.jsx
  src/pages/MainPage/components/MapMarker/EventMarkerContainer.jsx
  src/pages/MainPage/components/MyPage/MyActivities.jsx
Labels: 버그, 기능개발, 스타일링, 리팩토링

#46 Docs
  README.md
  src/api/myActivitesApi.js
  src/hooks/queries/myActivities/myActivityQuery.js
  src/main.jsx
  src/pages/MainPage/components/Detail/Review.jsx
  src/pages/MainPage/components/MyPage/MyActivities.jsx
  src/pages/MainPage/components/MyPage/MyActivityList.jsx
  src/pages/MainPage/components/MyPage/MyPage.jsx
  src/pages/MainPage/components/MyPage/Profile.jsx
Labels: 문서수정

#49 [project] 2차머지
  README.md
  index.html
  public/assets/favicon.ico
  src/api/myActivitesApi.js
  src/hooks/queries/auth/useLoginQuery.js
  src/hooks/queries/auth/useSignupQuery.js
  src/hooks/queries/auth/useUpdateProfileQuery.js
  src/hooks/queries/myActivities/myActivityQuery.js
  src/layout/Layout.jsx
  src/main.jsx
  src/pages/MainPage/MainPage.jsx
  src/pages/MainPage/components/AuthForm.jsx
  src/pages/MainPage/components/Calculator/Calculator.jsx
  src/pages/MainPage/components/Calculator/DateForm.jsx
  src/pages/MainPage/components/Calculator/ProcessBar.jsx
  src/pages/MainPage/components/Calculator/RankTags.jsx
  src/pages/MainPage/components/Detail/DetailModal.jsx
  src/pages/MainPage/components/Detail/Review.jsx
  src/pages/MainPage/components/Detail/ReviewItem.jsx
  src/pages/MainPage/components/MapMarker/EventMarkerContainer.jsx
  src/pages/MainPage/components/MyPage/MyActivities.jsx
  src/pages/MainPage/components/MyPage/MyActivityList.jsx
  src/pages/MainPage/components/MyPage/MyPage.jsx
  src/pages/MainPage/components/MyPage/Profile.jsx
  src/store/useAlertStore.js
  src/styles/CustomAlert/AlertProvider.jsx
  yarn.lock
Labels: 기능개발, 스타일링, 리팩토링

#50 [refactor] 마이페이지 리팩토링
  README.md
  src/constant/MyPageNav.js
  src/hooks/queries/myActivities/myActivityQuery.js
  src/main.jsx
  src/pages/MainPage/components/MyPage/MyActivities.jsx
  src/pages/MainPage/components/MyPage/MyActivityList.jsx
  src/pages/MainPage/components/MyPage/MyPage.jsx
  src/styles/.gitkeep
  src/styles/CustomAlert/hooks/useAlert.js
Labels: 리팩토링

#53 feat/오버레이 디자인 수정
  src/layout/components/Sidebar.jsx
  src/layout/components/SidebarHeader.jsx
  src/pages/MainPage/components/MapMarker/EventMarkerContainer.jsx
Labels: 스타일링

#54 Feat/마크 오버레이 디자인 수정
  src/pages/MainPage/components/MapMarker/EventMarkerContainer.jsx
Labels: 버그, 스타일링

#55 [style] 마이페이지 스타일링
  package.json
  src/hooks/queries/myActivities/myActivityQuery.js
  src/main.jsx
  src/pages/MainPage/components/MyPage/MyActivities.jsx
  src/pages/MainPage/components/MyPage/MyActivityList.jsx
  src/pages/MainPage/components/MyPage/MyPage.jsx
  src/pages/MainPage/components/MyPage/Profile.jsx
  src/reset.css
  yarn.lock
Labels: 스타일링

#56 [project] 3차 머지
  README.md
  package.json
  src/constant/MyPageNav.js
  src/hooks/queries/myActivities/myActivityQuery.js
  src/layout/components/Sidebar.jsx
  src/layout/components/SidebarHeader.jsx
  src/main.jsx
  src/pages/MainPage/components/Calculator/DateForm.jsx
  src/pages/MainPage/components/Detail/Favorite.jsx
  src/pages/MainPage/components/Detail/Review.jsx
  src/pages/MainPage/components/Detail/ReviewItem.jsx
  src/pages/MainPage/components/MapMarker/EventMarkerContainer.jsx
  src/pages/MainPage/components/MyPage/MyActivities.jsx
  src/pages/MainPage/components/MyPage/MyActivityList.jsx
  src/pages/MainPage/components/MyPage/MyPage.jsx
  src/pages/MainPage/components/MyPage/Profile.jsx
  src/reset.css
  src/store/useAlertStore.js
  src/styles/.gitkeep
  src/styles/CustomAlert/hooks/useAlert.js
  yarn.lock
Labels: 버그, 스타일링

#59 [project] 4차머지
  public/assets/favicon.ico
  src/api/apiInstance.js
  src/pages/MainPage/components/Modal/Modal.jsx
  src/pages/MainPage/components/MyPage/MyActivityList.jsx
Labels: 스타일링, 리팩토링

#60 [update] README.md
  README.md
Labels: 문서수정
